// Bundles content/agents/*.yaml into src/data/generated/agents.ts for the app.
// Runs before dev, build, and typecheck. Pass --watch to re-bundle when content changes.
import { mkdirSync, watch, writeFileSync } from "node:fs";
import { join } from "node:path";
import { contentDir, loadAgentContent } from "./lib/agent-content.mjs";

const outputFile = join(process.cwd(), "src/data/generated/agents.ts");

function bundle() {
  const { agents, failures } = loadAgentContent();
  if (failures.length) {
    console.error(`Agent content is invalid:\n${failures.map((failure) => `- ${failure}`).join("\n")}`);
    return false;
  }

  mkdirSync(join(process.cwd(), "src/data/generated"), { recursive: true });
  writeFileSync(
    outputFile,
    `// Generated by scripts/build-content.mjs from content/agents. Do not edit.\n` +
      `import type { AgentSource } from "@/types/agent";\n\n` +
      `export const agentSources: AgentSource[] = ${JSON.stringify(agents, null, 2)};\n`
  );
  console.log(`Bundled ${agents.length} agents into src/data/generated/agents.ts`);
  return true;
}

if (process.argv.includes("--watch")) {
  bundle();
  let timer;
  watch(contentDir, () => {
    clearTimeout(timer);
    timer = setTimeout(bundle, 100);
  });
  console.log(`Watching ${contentDir} for changes...`);
} else if (!bundle()) {
  process.exit(1);
}
